name: 'Ketch Publish'
description: 'Publish app to Ketch Marketplace'
inputs:
  command:
    description: 'Command'
    required: false
    default: 'publish'
  filename:
    description: 'Configuration filename'
    required: false
    default: 'ketch-manifest.yml'
  config:
    description: 'Environment filename'
    required: false
    default: '.ketchrc'
  token:
    description: 'Ketch token'
    required: true
  url:
    description: 'URL to Ketch Rest'
    required: false
    default: 'https://global.ketchapi.com/rest'
runs:
  using: 'docker'
  image: "docker://ghcr.io/ketch-com/ketch-cli:latest"
  env:
    KETCH_TOKEN: ${{ inputs.token }}
  args:
    - ${{ inputs.command }}
    - "--config"
    - ${{ inputs.config }}
    - "-f"
    - ${{ inputs.filename }}
    - "--token"
    - ${{ inputs.token }}
    - "--url"
    - ${{ inputs.url }}
branding:
  icon: 'share-2'
  color: 'purple'
