name: 'Ketch Publish'
description: 'Publish app to Ketch Marketplace'
inputs:
  command:
    description: 'Command'
    required: false
    default: 'publish'
  filename:
    description: 'Configuration filename'
    required: false
    default: 'ketch-manifest.yml'
  token:
    description: 'Ketch token'
    required: true
  with_url:
    description: 'With url prefix to Ketch Rest'
    required: false
    default: ''
  with_create:
    description: 'With flag indicating app create'
    required: false
    default: ''
runs:
  using: 'docker'
  image: "docker://ghcr.io/ketch-com/ketch-cli:latest"
  env:
    KETCH_TOKEN: ${{ inputs.token }}
  args:
    - ${{ inputs.command }}
    - "-f"
    - ${{ inputs.filename }}
    - ${{ inputs.with_url }}
    - ${{ inputs.with_create }}
branding:
  icon: 'share-2'
  color: 'purple'
