name: 'Ketch Publish'
description: 'Publish app to Ketch Marketplace'
inputs:
  command:
    description: 'Command'
    required: false
    default: 'publish'
  filename:
    description: 'Configuration filename'
    required: false
    default: 'ketch-manifest.yml'
  token:
    description: 'Ketch token'
    required: true
  url:
    description: 'URL to Ketch Rest'
    required: false
    default: 'https://global.ketchapi.com/rest'
  create:
    description: 'Flag indicating app create'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: "docker://ghcr.io/ketch-com/ketch-cli:latest"
  env:
    KETCH_TOKEN: ${{ inputs.token }}
    APP_WEBHOOK_URL: ${{ inputs.APP_WEBHOOK_URL }}
    APP_USER_AUTH_CALLBACK_URL: ${{ inputs.APP_USER_AUTH_CALLBACK_URL }}
    APP_SETUP_URL: ${{ inputs.APP_SETUP_URL }}
  args:
    - ${{ inputs.command }}
    - "-f"
    - ${{ inputs.filename }}
    - "--token"
    - ${{ inputs.token }}
    - "--url"
    - ${{ inputs.url }}
    - "--create"
    - ${{ inputs.create }}
branding:
  icon: 'share-2'
  color: 'purple'
