#!/usr/bin/env sh

# Code generated by shipbuilder init 1.21.0. DO NOT EDIT.

check_installed() {
  installed=$(which "$1")

  if [ -z "$installed" ]; then
    echo "ERROR: $1 is not installed."
    if [ "$CI" = "true" ]; then
      exit 1
    fi

    echo "Do you want to install and continue? Y/N"
    read install
    install=$(echo "$install" | tr "[:lower:]" "[:upper:]")
    if [ "$install" = "Y" -o "$install" = "YES" ]; then
      sh -c "$2"
    fi

    export installed=$(which "$1")
    if [ -z "$installed" ]; then
      echo "ERROR: $1 is not installed."
      echo "Install $1 using '$2'."
      exit 1
    fi
  fi
}

brew_installed() {
  if [ "$CI" != "true" ]; then
    check_installed brew '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    brew=$installed
  fi
}

brew_install() {
  brew_installed
  check_installed $1 "$brew install ${2:-$1}"
}

go_installed() {
  brew_install go
  go=$installed
}

go_install() {
  go_installed
  go get $1
  go install $1
  installed="go run $1"
}

github_installed() {
  brew_install gh
  github="$installed"
}

git_installed() {
  brew_install git
  git="$installed"
}

docker_installed() {
  brew_install docker "homebrew/cask/docker"
  docker="$installed"
}

yq_installed() {
  brew_install yq
  yq="$installed"
}

jq_installed() {
  brew_install jq
  jq="$installed"
}

check() {
  for i in $*; do
    "${i}_installed"
  done
}
