// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	app "go.ketch.com/lib/app"

	mock "github.com/stretchr/testify/mock"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// ValidateApp provides a mock function with given fields: ctx, _a1
func (_m *Validator) ValidateApp(ctx context.Context, _a1 *app.App) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *app.App) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateBytes provides a mock function with given fields: ctx, b
func (_m *Validator) ValidateBytes(ctx context.Context, b []byte) error {
	ret := _m.Called(ctx, b)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
