name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      SNYK_AUTH_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        submodules: true
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/cache@v3.0.1
      with:
        path: /home/runner/go
        key: v1-go-mod-${{ hashFiles('go.sum') }}
        restore-keys: v1-go-mod-
    - uses: winchci/actions-golang@v1
